<a href="https://colab.research.google.com/github/AlexHarry17/Reinforcement_Learning/blob/master/Deep_Learning_Course/FrozenLake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code is sourced from https://github.com/simoninithomas/Deep_reinforcement_learning_Course/blob/master/Q%20learning/FrozenLake/Q%20Learning%20with%20FrozenLake.ipynb from the course https://simoninithomas.github.io/Deep_reinforcement_learning_Course/#syllabus

In [3]:
!pip install numpy
!pip install gym

In [0]:
import numpy as np
import gym
import random

In [0]:
env = gym.make("FrozenLake-v0")

In [9]:
action_size=env.action_space.n
state_size=env.observation_space.n
qtable=np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
total_episodes = 15000
learning_rate=0.8
max_steps = 99
gamma=0.95
epsilon=1.0
max_epsilon=1.0
min_epsilon=0.01
decay_rate=0.005


In [0]:
rewards = []

# Loops until learning time is up
for episode in range(total_episodes):
  state=env.reset()
  step = 0
  done = False
  total_rewards=0
  
  for step in range(max_steps):
    exp_tradeoff = random.uniform(0,1)
    # Decide whether to explore or not
    if exp_tradeoff > epsilon:
      action = np.argmax(qtable[state,:])
    else:
      action = env.action_space.sample()
    
    # Get new state, reward, if round is done
    new_state, reward, done, info = env.step(action) 
    # Update the qtable
    qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state,:])- qtable[state,action])
    
    total_rewards += reward
    state = new_state
    if done: break

  # Reduce epsilon for les exploration
  epsilon = min_epsilon + (max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)
  rewards.append(total_rewards)



In [15]:
print("Score: ", sum(rewards)/total_episodes)
print(qtable)

Score:  0.492
[[3.06711175e-01 1.18448397e-01 5.75410692e-02 8.03160599e-02]
 [1.82138365e-05 1.10635178e-03 3.78261066e-03 8.04285676e-02]
 [1.60087703e-01 1.42612711e-02 1.94373233e-02 1.89922787e-02]
 [1.47376186e-04 4.82749280e-03 4.64716044e-03 1.77048628e-02]
 [3.51623543e-01 1.39170387e-02 1.36372254e-02 2.03411806e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.96001123e-05 1.15388772e-03 6.99251134e-01 1.63188829e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.57358351e-03 1.77115875e-02 9.97748438e-02 6.07060173e-01]
 [2.00424737e-02 7.68691161e-01 2.92065546e-02 4.17913118e-02]
 [9.02920454e-01 9.90775920e-03 1.70438763e-02 3.11513358e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.65977019e-02 1.64533862e-02 8.12217577e-01 1.95553113e-02]
 [3.24104356e-01 9.99839985e-01 3.01573516e-01 1.29007213e-01]
 [0.00000000e+00 0.00000000e+00 0.0000000

In [19]:
# Play FrozenLake

env.reset()
state = env.reset()
step = 0
done = False
print("--------------------------------")
print('Episode: ', episode)
print("--------------------------------")

for step in range(max_steps):
  action = np.argmax(qtable[state,:])
  new_state, reward, done, info = env.step(action)
  env.render()
  if done: 
    env.render()
    print('# Steps taken: ', step)
    break
  state = new_state
env.close()

--------------------------------
Episode:  4
--------------------------------
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH