<a href="https://colab.research.google.com/github/AlexHarry17/Reinforcement_Learning/blob/master/Deep_Learning_Course/Taxi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To learn and understand deep learning I am folling this course: https://simoninithomas.github.io/Deep_reinforcement_learning_Course/.   This is a Q Learning network to play the game taxi.  The code is sourced from https://github.com/simoninithomas/Deep_reinforcement_learning_Course/blob/master/Q%20learning/Taxi-v2/Q%20Learning%20with%20OpenAI%20Taxi-v2%20video%20version.ipynb

In [0]:
import numpy as np
import gym
import random

In [0]:
# Create the environment
env = gym.make('Taxi-v2')


In [4]:
# Create the q table
action_space = env.action_space.n
state_size = env.observation_space.n
qtable = np.zeros((state_size, action_space))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [0]:
total_episodes = 50000
total_test_episodes = 100
max_steps = 99
learning_rate = 0.7
gamma = 0.618
epsilon = 1.0
min_epsilon = 0.01
max_epsilon = 1.0
decay_rate = 0.01

In [0]:
for episode in range(total_episodes):
  state = env.reset()
  step = 0
  done = False
  for step in range(max_steps):
    # Random number to decide on exploration
    exp_tradeoff = random.uniform(0,1)
    if exp_tradeoff > epsilon:
      action = np.argmax(qtable[state,:])
    else:
      action = env.action_space.sample()

    new_state, reward, done, info = env.step(action)
    # Update Qtable
    qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * 
                                    np.max(qtable[new_state, :]) - qtable[state, action])
    
    state = new_state
    if done: break
  
  # Reduce learning rate
  epsilon = min_epsilon + (max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)


In [13]:
#Play taxi
rewards = []
for episode in range(total_test_episodes):
  state = env.reset()
  step = 0
  total_reward = 0

  for step in range(max_steps):
    env.render()
    action = np.argmax(qtable[state,:])
    new_state, reward, done, info = env.step(action)
    total_reward+=reward
    if done:
      rewards.append(total_reward)
      break
    state = new_state
env.close()
print("Score: ", sum(rewards)/total_test_episodes)

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : :_: : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| :_: : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |